language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

os:
  - linux
  - windows
  - osx

cache: cargo

script:
  - cargo build
  - cargo build --all-features
  - cargo build --release
  - cargo build --release --all-features
  - cargo clippy -- -D warnings
  - cargo clippy --all-features -- -D warnings
  - cargo test --release --all-features
  - cargo test
  - cargo doc --all-features --no-deps
