[package]
name = "flexi_logger"
version = "0.8.1"
authors = ["emabee <meinolf.block@sap.com>"]
description = """
A logger that writes logs to stderr or to a fresh file, \
or to a sequence of files in a configurable folder. \
It allows custom logline formats, and it allows changing the log specification at runtime. \
It also allows defining additional log streams, e.g. for alert or security messages.\
"""
keywords = ["file", "logger"]
license = "MIT/Apache-2.0"
repository = "https://github.com/emabee/flexi_logger"


[features]
default = []
specfile = ["serde","toml","notify", "serde_derive"]

[dependencies]
chrono = "0.4"
glob = "0.2"
regex = "0.2"
log = { version = "0.4", features = ["std"] }
serde = { version = "1.0", optional = true }
toml = { version = "0.4", optional = true }
notify = { version = "4.0", optional = true }
serde_derive = {version = "1.0", optional = true}

[dev-dependencies]
serde_derive = "1.0"
