[package]
name = "flexi_logger"
version = "0.1.3"
authors = ["emabee <meinolf.block@sap.com>"]
description = "A flexible logger that can write to stderr or to log files"
keywords = ["file", "logger"]
license = "MIT/Apache-2.0"
repository = "https://github.com/emabee/flexi_logger"


[dependencies]
log = "0.3"
regex = "0.1"
time = "0.1"
