[package]
name = "flexi_logger"
version = "0.1.3"
authors = ["emabee <meinolf.block@sap.com>"]
description = "A flexible logger that can write to stderr or to log files"
keywords = ["file", "logger"]


[dependencies]
log = "*"
regex = "*"
time = "*"
